### ISSUE TITLE
No data collected in 'core'-group

### ISSUE THREAD

**Issue by TheMehli** [powerapi-ng/hwpc-sensor#44]
Hello,

I am trying to set up the HWPC Sensor with SmartWatts. As a first measure, I have tried to set both up according to the PowerAPI documentation. However the output of the HWPC Sensor doesn't correspond to what I expect. Data from the 'rapl' and 'msr' groups seem to be collected and passed on to MongoDB just fine, but there is no data from the 'core' group.

This is my config file for the Sensor:

```
{
  "name": "sensor",
  "verbose": true,
  "frequency": 500,
  "output": {
    "type": "mongodb",
    "uri": "mongodb://127.0.0.1",
    "database": "mongo_destination",
    "collection": "report_0"
  },
  "system": {
    "rapl": {
      "events": ["RAPL_ENERGY_PKG"],
      "monitoring_type": "MONITOR_ALL_CPU_PER_SOCKET"
    },
    "msr": {
      "events": ["TSC", "APERF", "MPERF"]
    }
  },
  "container": {
    "core": {
      "events": [
        "CPU_CLK_UNHALTED:REF_P",
	"CPU_CLK_UNHALTED:THREAD_P",
        "LLC_MISSES",
	"INSTRUCTIONS_RETIRED"
      ]
    }
  }
}
```

My output corresponds to the example given here: https://powerapi.org/reference/reports/reports/#hwpc-report
But I am only getting the second timestamp with the 'rapl' and 'msr' groups.

I am running on Debian 12 with an Intel i5-10210U.

Is there a way I can get this data? Since SmartWatts doesn't generate reports and I suspect it's because of these missing datapoints.

Thank you.

**Comment by TheMehli** [comment]
Hello,

sure:

```
{
  "verbose": true,
  "stream": true,
  "input": {
    "puller": {
      "model": "HWPCReport",
      "type": "mongodb",
      "uri": "mongodb://127.0.0.1",
      "db": "mongo_destination",
      "collection": "report_0"
    }
  },
  "output": {
    "pusher_power": {
      "type": "influxdb2",
      "uri": "127.0.0.1",
      "port": 8086,
      "db": "test_results",
      "org": "admin",
      "token": "myToken"
    }
  },
  "cpu-base-freq": 1600,
  "cpu-error-threshold": 2.0,
  "disable-dram-formula": true,
  "sensor-reports-frequency": 500
}
```

**Comment by roda82** [comment]
Thank you for the configuration. Can you indicate `PowerReport` as model in the `pusher_power` output and test again ?

**Comment by TheMehli** [comment]
Thank you, this seems to indeed have done the trick. However, I am still confused as to why I seem to not be getting the data from the core group. Is this expected behavior and does that change the accuracy of my Power Reports?

**Comment by roda82** [comment]
I just installed Debian 12 on a Intel i7-10610U, which belongs to the same processor family as yours. I'm using a kernel version 6.1.0-13-amd64. I am able to see core group values for targets different to `all`. Did you create a cgroup and associated to the process that you want to monitor ?

**Comment by roda82** [comment]
Can also provide us the logs related to `HWPC Sensor` ? And can you confirm us that you activated cgroup V1 ?
